runtime: python311

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F2  # or F1, F4 depending on your needs

env_variables:
  PYTHONUNBUFFERED: '1'

handlers:
- url: /staticfile
  static_dir: staticfile

- url: /design
  static_dir: design

- url: /assets
  static_dir: assets

- url: /.*
  script: auto
